apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "sdchart.fullname" . }}-aws-sqs-queue-scaledobject
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
spec:
  cooldownPeriod: 60
  maxReplicaCount: 20
  minReplicaCount: 1
  pollingInterval: 1
  scaleTargetRef:
    name: sd-webui-inference-api
  triggers:
  - authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      awsRegion: us-west-2
      identityOwner: operator
      queueLength: "10"
      queueURL: https://sqs.us-west-2.amazonaws.com/057313215210/SdOnEksDataPlaneSandbox-eksClusterInputQueue19310EEB5-yK9YLbLTv5rI
    type: aws-sqs-queue